[tool.poetry]
name = "django-material-admin"
version = "0.1.0"
description = ""
authors = ["jp <jmartinez@clk.com.uy>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
